[server]
headless = true
enableStaticServing = true

[theme]
primaryColor = "#F43F5E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
